services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawler
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./data/screenshots:/app/data/screenshots

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
      WATCHPACK_POLLING: "true"    
      CHOKIDAR_USEPOLLING: "true"  
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
  frontend_node_modules:
